### PR TITLE
add chainese

### PR DESCRIPTION
**Pull request by sanshu-rom**
add chainese

### CODE REVIEW

**Comment by ericswpark** [comment]
Please submit those commits to our Gerrit system: review.blissroms.com

Thanks!

**Comment by sanshu-rom** [comment]
I don't know bliss's SSH key. Please submit it for me. @ideaman924

**Comment by ericswpark** [comment]
I've added the commit to our Gerrit system for you: https://review.blissroms.com/c/platform_packages_apps_Settings/+/4447

In the future, please use the appropriate channels to submit your commit. This pull request can now be closed. Thanks!

**Comment by sanshu-rom** [comment]
OK,thanks.

**Comment by ericswpark** [comment]
Requesting admin to close this PR. @Jackeagle

**Pull request closed without merging**
